[[Valhalla]]
arch = "aarch64"
git-tree-sha1 = "62b6e63a247eaf02dfb64013953b37ad505c116d"
os = "macos"

    [[Valhalla.download]]
    sha256 = "a3d130d566b7bf67dea8562811e5b47c9e5c9c9d600d35d54a94df8ec9fcc259"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.aarch64-apple-darwin.tar.gz"
[[Valhalla]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fca0a09a8f577d528c2ec3a1cb88369da070780"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "4cfceb55ae6c3cfdf62a6c8fec129b745f5b64235e7f76e581de453fc3faf781"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Valhalla]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b037f9be197eba4fbde9e4e52d01b355001ca4b"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "ab16a204999d92981155a34fbf2bbb58f94bdb144755f9339683db3f40a48064"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Valhalla]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc35a4239e787f0d6ae4db76047063fce7dad075"
libc = "musl"
os = "linux"

    [[Valhalla.download]]
    sha256 = "69d54389ac9ca46a9801a0199fcba1ffbba0f6949b5c4db245e97899633d1639"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.aarch64-linux-musl-cxx03.tar.gz"
[[Valhalla]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0dbbff9441491cfee3a3ea55f285ce2504fee955"
libc = "musl"
os = "linux"

    [[Valhalla.download]]
    sha256 = "9d7af802fd0fac6372ee2fb7a96836594623cc4274ea22d582f6b5def2e90c88"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.aarch64-linux-musl-cxx11.tar.gz"
[[Valhalla]]
arch = "aarch64"
git-tree-sha1 = "b2f7d1c53ac6e640825bef036890f8a684df0f78"
os = "freebsd"

    [[Valhalla.download]]
    sha256 = "ed38b148cb348aa8cc478ec8e6878d5a63c0bd67ab939cc5dc3bf484f5d411f8"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.aarch64-unknown-freebsd.tar.gz"
[[Valhalla]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc26188a22130336468ff430c4925c2f38764dee"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "123b3ba00d2bd76edbc9ca8e104b0e8b7ab2ee1f5d3fd3415468244c8a1bf86d"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Valhalla]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9c452692f3157bb07fd0d694fa76c6cb8c631b1"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "5807fca14f34f945432145c08bd344d9a5d342e27c121483400ee22efb266ffa"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Valhalla]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5aa9d5384bea70e3116ddf74abcf5ebffe6ad70"
libc = "musl"
os = "linux"

    [[Valhalla.download]]
    sha256 = "a01c590cf3717e4cefe07a50da5b914a8ea96312799a6989e5be0db9aecc0543"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Valhalla]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13c5b14b6fcc65e1b03bd8f5374815300c1fbb4d"
libc = "musl"
os = "linux"

    [[Valhalla.download]]
    sha256 = "331b8a815c38df5440d4257ec2050bf1d3eeaf047b6b742865a9645cd03b441b"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Valhalla]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa7d6b7f83de1523166a8faa4ea6bfa323fc2970"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "c9438c6996f5ee9098fb65d65b42def624dc2ae4148701569accba81787e404f"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Valhalla]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5cf49c9a89258520d301d3b1889d2b028c6ddb1"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "35753d525070c20452bf7226c356ef48979bf202e347f0920d3045403ef26ec0"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Valhalla]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eed74d78b2340b97700c6385b8728ce5b719eb83"
libc = "musl"
os = "linux"

    [[Valhalla.download]]
    sha256 = "0d51e5a95d1edb4aeec4531b267618b5d96b8f33083a23a6e5ae03ce748cdff4"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Valhalla]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "805224ff89d607d26a1b9e9d68690e239640f2eb"
libc = "musl"
os = "linux"

    [[Valhalla.download]]
    sha256 = "2a4a03aea878e3ad1a2fab16888ab2cd24a331e8e24b1a8fd2a06e0c1f31a34f"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Valhalla]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3590987366dd37d1eebfa046ee758c0804e2c86"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "37404b7b654ae383e0012e55f0a7e936b4e00ac854789567e9a18e1baf03a463"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.i686-linux-gnu-cxx03.tar.gz"
[[Valhalla]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1c5e39760e8f3364677fa7c8f864a9a4aa8a565"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "6f5913c5e34730ac5ba3d1bfbb4665cdf66a4e9994406877960b617a60251e42"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.i686-linux-gnu-cxx11.tar.gz"
[[Valhalla]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cc82ba586a35c75964bd57bcfb450760550f744"
libc = "musl"
os = "linux"

    [[Valhalla.download]]
    sha256 = "a425d90782c7a707b73e43084ecda06cecbf200aef73d9d35c89a06fbfbaffe0"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.i686-linux-musl-cxx03.tar.gz"
[[Valhalla]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "feb7c1869c9436b4d3bcae6a88904f10b44884ce"
libc = "musl"
os = "linux"

    [[Valhalla.download]]
    sha256 = "b1ce3fd26fc489e3ea81c9040dcf7cbd2c838135118363b84df02eec55e78531"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.i686-linux-musl-cxx11.tar.gz"
[[Valhalla]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "921a0b5a8ab6e5eb582aafeec07d9e7a789666e1"
os = "windows"

    [[Valhalla.download]]
    sha256 = "f5774a89ec87f1980549118f45f3782683626f709e73e5f66bd9b813ac660f88"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.i686-w64-mingw32-cxx03.tar.gz"
[[Valhalla]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b0437125e8b0c7c96b78f1118a10ef8b447f92b"
os = "windows"

    [[Valhalla.download]]
    sha256 = "421502fcd2a030ed369d2c38d4cfccdba813b8ba0059df6b5213eb674fa4c07f"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.i686-w64-mingw32-cxx11.tar.gz"
[[Valhalla]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f34e326c86fe2e20a5efabc663875ea9f3c1e79"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "9920cd3fb25b21ccbba6b976a8e8856e23f778c92a550473bad6a0b0eefc4dc6"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Valhalla]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c4232bdfe3bf7e79e3905174527148ec7bb9648"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "dae2e424700dcbc55f6d2a73b9b4348f8208e0afe4d6125c79bed442c8c01b0b"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Valhalla]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98121e1fdee5aec6f0c93a2294c6d8ce40dfe294"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "9dbc094d703f40db3c2d4a6c2e285185ef72c6b908e1bd7bf323181618dab0b8"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.riscv64-linux-gnu-cxx03.tar.gz"
[[Valhalla]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "812f4925ec9d226eaabf08203e24433e99cf50bb"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "0e636f65fcd7d263ea1284c4423628564669f7cd444b7567666951c7b260f568"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.riscv64-linux-gnu-cxx11.tar.gz"
[[Valhalla]]
arch = "x86_64"
git-tree-sha1 = "60d8dd80c83a2f1d94076ad5b30dc2c3e35d8516"
os = "macos"

    [[Valhalla.download]]
    sha256 = "6462c242a47c5aa00953bb3b1e0725d6d2ea20c710f18d7c2ffa2c6c92053838"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.x86_64-apple-darwin.tar.gz"
[[Valhalla]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45d2742e20be660b770c970cf3beb86cfa6b7f55"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "00cc0e33a5615b38831b4a1004cde9d20d057c7bbb46481c47604b0c38376409"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Valhalla]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4b9c3c4840a2c9b992a9496ad924ebad8c85858"
libc = "glibc"
os = "linux"

    [[Valhalla.download]]
    sha256 = "c45901429302fc33c99ad03db2f71015af37a9f4abbb70abcc516ecb62ea83c5"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Valhalla]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "203786dad9c53b7eb96310d44fda6a7f38688cdb"
libc = "musl"
os = "linux"

    [[Valhalla.download]]
    sha256 = "764555430adc472fe5d4ea6a1da68fbe7349f92bdb1f3d99acb12869b6235ea4"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.x86_64-linux-musl-cxx03.tar.gz"
[[Valhalla]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "221199d85baecad3d819cfd2aa01d2e8c95f82a8"
libc = "musl"
os = "linux"

    [[Valhalla.download]]
    sha256 = "5d6c2c86ef7ce01887d41bda5d968deacc68f9a6af80ff323897768ee47ee0ce"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.x86_64-linux-musl-cxx11.tar.gz"
[[Valhalla]]
arch = "x86_64"
git-tree-sha1 = "5a62828d490589830b9841c6a3f101805c85b772"
os = "freebsd"

    [[Valhalla.download]]
    sha256 = "82d1b8950d78575777211c4a65dd069fc860ae651b882efb287e2aa144a2ddf1"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.x86_64-unknown-freebsd.tar.gz"
[[Valhalla]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3883a70becdac782e38412ad5392cf224fae9d34"
os = "windows"

    [[Valhalla.download]]
    sha256 = "1e82fa11bc81a308e678063bcb82ea7e2cbd0c6d7772dea6269391fb231b969a"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Valhalla]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c545c7cb1fe03d036521f218b94fdca6cb4d78e"
os = "windows"

    [[Valhalla.download]]
    sha256 = "d07c946cce12585a656bd796819a6ea63efadf1186a5818d6a5b79833fa6d0f5"
    url = "https://github.com/JuliaBinaryWrappers/Valhalla_jll.jl/releases/download/Valhalla-v3.5.1+0/Valhalla.v3.5.1.x86_64-w64-mingw32-cxx11.tar.gz"
