# Autogenerated wrapper script for Valhalla_jll for aarch64-apple-darwin
export libvalhalla

using boost_jll
using GEOS_jll
using LibCURL_jll
using Lz4_jll
using protoc_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("Valhalla")
JLLWrappers.@declare_library_product(libvalhalla, "@rpath/libvalhalla.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header(boost_jll, GEOS_jll, LibCURL_jll, Lz4_jll, protoc_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libvalhalla,
        "lib/libvalhalla.3.3.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
